"""Emit a ready-to-use ``EvolutionTemplate`` Python file from an Activity spec.

The output mirrors the shape of ``templates/inline.py`` but uses the
generic ``_pick``-style output lookup from ``activity/adapters.py`` so
it works for any user-designed Activity (not just one whose outputs
match inline's specific pin names).

Usage::

    from .codegen import generate_template_py
    src = generate_template_py(activity_spec_dict, class_name="StudioInline",
                                template_name="studio_inline")
    Path("templates/studio_inline.py").write_text(src)
"""

from __future__ import annotations

import datetime as _dt
import json
import keyword
import re
from typing import Any

from ..activity.registry import default_registry
from ..activity.spec import Activity
from ..activity.validator import ActivityValidationError, validate


class CodegenError(Exception):
    """Raised when a spec cannot be emitted as a valid template file."""


_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _check_identifier(name: str, kind: str) -> None:
    if not isinstance(name, str) or not _IDENT_RE.match(name):
        raise CodegenError(f"{kind} must be a valid Python identifier, got {name!r}")
    if keyword.iskeyword(name):
        raise CodegenError(f"{kind} {name!r} is a Python keyword")


def _dict_literal(obj: Any, indent: int = 0) -> str:
    """Render a JSON-safe value as a Python source literal.

    ``Activity.to_json()`` emits only strings, ints, bools, None, lists, and
    dicts — a strict subset of Python.  ``json.dumps`` with ``indent`` gives
    us a clean multi-line form; we then swap the tokens that differ between
    JSON and Python.
    """
    text = json.dumps(obj, indent=indent or None, sort_keys=False)
    # JSON → Python token swap.  Strings cannot contain these exact tokens
    # (``true``/``false``/``null`` appear as JSON strings with quotes, which
    # leaves the unquoted forms unambiguous after json.dumps).
    text = re.sub(r"(?<![A-Za-z0-9_\"])true(?![A-Za-z0-9_\"])", "True", text)
    text = re.sub(r"(?<![A-Za-z0-9_\"])false(?![A-Za-z0-9_\"])", "False", text)
    text = re.sub(r"(?<![A-Za-z0-9_\"])null(?![A-Za-z0-9_\"])", "None", text)
    return text


def generate_template_py(
    activity_spec: dict[str, Any],
    *,
    class_name: str,
    template_name: str,
) -> str:
    """Build the Python source for a drop-in EvolutionTemplate.

    Args:
        activity_spec: JSON-shaped Activity (from ``Activity.to_json()``).
        class_name: Python class name for the template (e.g. ``StudioInline``).
        template_name: short identifier returned by ``.name`` (e.g. ``studio_inline``).

    Returns:
        Python source code as a string.

    Raises:
        CodegenError: if names are invalid or the spec fails validation.
    """
    _check_identifier(class_name, "class_name")
    if not isinstance(template_name, str) or not template_name:
        raise CodegenError("template_name must be a non-empty string")

    # Build + validate the Activity first so we never emit broken templates.
    try:
        activity = Activity.from_json(activity_spec)
    except Exception as e:
        raise CodegenError(f"Activity spec is malformed: {e}") from e
    try:
        validate(activity, default_registry())
    except ActivityValidationError as e:
        raise CodegenError(f"Activity failed validation: {e}") from e

    # Re-canonicalise via to_json so whatever we embed is exactly what the
    # runtime would read back.
    canonical = activity.to_json()
    spec_literal = _dict_literal(canonical, indent=2)

    timestamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    src = f'''"""Generated by navigation/studio on {timestamp}.

This file is a self-contained ``EvolutionTemplate``.  It embeds the
``Activity`` spec as a module-level literal and runs it through the
shared ``ActivityRuntime`` at execution time.

Placement: this file MUST live at
``agent_evolve/algorithms/navigation/templates/{template_name}.py`` —
the relative imports (``..activity``, ``.base``) resolve correctly only
there.  Use as follows::

    from agent_evolve.algorithms.navigation.templates.{template_name} import {class_name}
    from agent_evolve.algorithms.navigation.engine import NavigationEngine

    engine = NavigationEngine(config, template={class_name}(engine=None))

``NavigationEngine`` accepts any ``EvolutionTemplate`` instance via the
``template=`` kwarg, so no edits to ``templates/__init__.py`` are required.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from ..activity.registry import default_registry
from ..activity.runtime import ActivityRuntime, RunContext
from ..activity.spec import Activity
from .base import EvolutionTemplate

if TYPE_CHECKING:
    from ....contract.workspace import AgentWorkspace
    from ....engine.versioning import VersionControl
    from ....types import StrategyTree
    from ..engine import NavigationEngine

logger = logging.getLogger(__name__)


ACTIVITY_SPEC: dict[str, Any] = {spec_literal}


class {class_name}(EvolutionTemplate):
    """Generated template wrapping the embedded Activity."""

    def __init__(self, engine: "NavigationEngine"):
        self.engine = engine
        self._activity = Activity.from_json(ACTIVITY_SPEC)
        self._registry = default_registry()

    @property
    def name(self) -> str:
        return {template_name!r}

    def execute(
        self,
        vc: "VersionControl",
        solver_workspace: "AgentWorkspace",
        batch_results: list[dict[str, Any]],
        tree: "StrategyTree",
        evo_number: int,
        routing_log_path: Path | None,
    ) -> dict[str, Any]:
        runtime = ActivityRuntime(self._registry)
        ctx = RunContext(registry=self._registry, runtime=runtime)
        ctx.extra["engine"] = self.engine

        available = {{
            "workspace": solver_workspace,
            "git": (vc, tree),
            "batch": batch_results,
            "cfg": self.engine.config,
            "evo_number": evo_number,
            "routing_log": str(routing_log_path) if routing_log_path else "",
        }}
        declared = {{p.id for p in self._activity.parameters}}
        bindings = {{k: v for k, v in available.items() if k in declared}}

        outputs = runtime.run(self._activity, bindings, ctx=ctx)

        return {{
            "evo_number": evo_number,
            "mutated": _pick(outputs, "mutated", default=False),
            "plan": _pick(outputs, "plan", default={{}}),
            "branches": tree.branch_names(),
            "trajectory": list(ctx.trace),
        }}


def _pick(outputs: dict[str, Any], name: str, *, default: Any) -> Any:
    """Look up a value by Activity out-parameter name.

    Falls back to scanning any ``"<node>.<pin>"`` key ending in ``.name``
    so templates whose Activity writes to a named node pin (rather than
    an out-parameter) still work.
    """
    if name in outputs:
        return outputs[name]
    suffix = "." + name
    for key, value in outputs.items():
        if key.endswith(suffix):
            return value
    return default
'''
    return src
